apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress-srv
    annotations:    # helps ingress to understands that we are feeding some routing rules
        kubernetes.io/ingress.class: nginx
spec:
    rules:  # routing rules (need to make a proxy on localhost as well...)
        - host: posts.com
          http:
            paths:
                - path: /posts
                  backend:
                    serviceName: posts-clusterip-srv
                    servicePort: 4000   # same PORT as service port