apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts  # ~ classname to htmls
    spec:
      containers:
        - name: posts
          image: shubhamjain2908/posts